#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : setuptools-markdown
Version  : 0.2
Release  : 2
URL      : https://files.pythonhosted.org/packages/48/56/b5b3b690c293263a9664655d29751da2d14f4e381e06799cc77e87e1d74f/setuptools-markdown-0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/48/56/b5b3b690c293263a9664655d29751da2d14f4e381e06799cc77e87e1d74f/setuptools-markdown-0.2.tar.gz
Summary  : Use Markdown for your project description
Group    : Development/Tools
License  : MIT
Requires: setuptools-markdown-python = %{version}-%{release}
Requires: setuptools-markdown-python3 = %{version}-%{release}
Requires: pypandoc
BuildRequires : buildreq-distutils3
BuildRequires : pypandoc

%description
setuptools-markdown
===================
Use `Markdown <http://daringfireball.net/projects/markdown/>`__ for your
project description

%package python
Summary: python components for the setuptools-markdown package.
Group: Default
Requires: setuptools-markdown-python3 = %{version}-%{release}

%description python
python components for the setuptools-markdown package.


%package python3
Summary: python3 components for the setuptools-markdown package.
Group: Default
Requires: python3-core

%description python3
python3 components for the setuptools-markdown package.


%prep
%setup -q -n setuptools-markdown-0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557449953
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
